{ lib, pkgs, ... }:

let
  repoRoot = ../../..;

  # Only the files the build actually reads. The docs markdown lives outside
  # docs-site/, so the source has to be the repo root with everything else
  # filtered out — otherwise every unrelated commit would rebuild the site.
  #
  # src/content/docs is excluded on purpose: it is generated by
  # scripts/sync-docs.mjs during the build and is gitignored, so including the
  # working-tree copy would make the derivation depend on local state. It is
  # absent from the git-tracked source the flake actually sees, which is why
  # the exclusion needs `maybeMissing`.
  siteSrc = lib.fileset.toSource {
    root = repoRoot;
    fileset = lib.fileset.difference (lib.fileset.unions [
      (repoRoot + "/docs")
      (repoRoot + "/README.md")
      (repoRoot + "/CLAUDE.md")
      (repoRoot + "/docs-site/package.json")
      (repoRoot + "/docs-site/pnpm-lock.yaml")
      (repoRoot + "/docs-site/astro.config.mjs")
      (repoRoot + "/docs-site/tsconfig.json")
      (repoRoot + "/docs-site/scripts")
      (repoRoot + "/docs-site/src")
    ]) (lib.fileset.maybeMissing (repoRoot + "/docs-site/src/content/docs"));
  };

  # Astro Starlight, built at Nix eval time. No runtime server and no secrets —
  # nginx serves dist/ straight from the store, exactly like
  # belle-watson-studios.nix.
  #
  # The build runs `node scripts/sync-docs.mjs` first, which copies ../docs into
  # the Starlight content collection and adds the frontmatter Starlight needs.
  # That is why editing docs/*.md is all it takes to change the site.
  #
  # A change to the lockfile changes pnpmDeps.hash. The first build then fails
  # with a hash mismatch; copy the "got:" value Nix prints into the hash below.
  site = pkgs.stdenv.mkDerivation (finalAttrs: {
    pname = "nix-of-time-docs";
    version = "0.1.0";
    src = siteSrc;
    sourceRoot = "${finalAttrs.src.name}/docs-site";

    nativeBuildInputs = [
      pkgs.nodejs_22
      pkgs.pnpm_9
      pkgs.pnpm_9.configHook
    ];

    pnpmDeps = pkgs.pnpm_9.fetchDeps {
      inherit (finalAttrs)
        pname
        version
        src
        sourceRoot
        ;
      fetcherVersion = 2;
      hash = "sha256-adRSg9ycFqUd8LB+wsWH/BztyonnlR0hoM4J+DBDXqo=";
    };

    # Astro phones home unless told not to, and a sandboxed build has no
    # network — the attempt only costs time.
    env.ASTRO_TELEMETRY_DISABLED = "1";

    buildPhase = ''
      runHook preBuild
      pnpm run build
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall
      cp -r dist $out
      runHook postInstall
    '';
  });
in
{
  # ── Documentation site ──────────────────────────────────────────────────────
  # Port: 4209 (localhost only, fronted by Pangolin/Newt → docs.ericsharma.xyz)
  # State: none. The site is a pure function of the repo.
  # NOT backed up — it rebuilds from the flake.
  #
  # Add the Pangolin route once, by hand:
  #   docs.ericsharma.xyz → 127.0.0.1:4209
  services.nginx = {
    enable = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;

    virtualHosts."docs.ericsharma.xyz" = {
      listen = [
        {
          addr = "127.0.0.1";
          port = 4209;
        }
      ];
      root = "${site}";

      # Astro builds with `format: "directory"`, so every page is
      # <slug>/index.html. End the chain with `=404` rather than /404.html —
      # naming the file directly would serve the styled page with a 200 status,
      # which lies to crawlers and to curl. `error_page` below renders it.
      locations."/" = {
        tryFiles = "$uri $uri/ $uri/index.html =404";
      };

      # Content-hashed filenames, so they can be cached forever.
      locations."/_astro/".extraConfig = ''
        add_header Cache-Control "public, max-age=31536000, immutable" always;
      '';

      # The Pagefind search index changes on every build and shares no hash
      # with the page that loads it.
      locations."/pagefind/".extraConfig = ''
        add_header Cache-Control "no-cache" always;
      '';

      extraConfig = ''
        error_page 404 /404.html;
      '';
    };
  };
}
