{
  config,
  lib,
  pkgs,
  ...
}:

# ── Portless LAN proxy — friendly *.local URLs for every LAN service ─────────
# Ports: 80 (proxy), 5353/udp (mDNS via avahi)
# State: /var/lib/portless — CA cert, route registrations, npm state
# Names: <alias>.local, e.g. http://sonarr.local, http://immich.local
# NOT backed up — every route is declared here, and no state matters after a
# reinstall (the CA can be regenerated by wiping the state dir).
#
# LAN mode publishes each alias as an mDNS record through avahi, so any device
# on the Wi-Fi resolves the name without touching /etc/hosts or the router's
# DNS. `services.avahi.publish` below is what makes the announcements go out;
# portless drives it via `avahi-publish-address`.
#
# HTTPS is disabled. Portless mints its own CA to serve *.local over TLS, and
# every client device would then need that CA installed once. For LAN-only
# UIs that already have no login (SABnzbd, Prowlarr, *arrs), the trust dance
# is worth more than the padlock. Flip `services.portless.tls` if that ever
# changes.
#
# ── Sharing across hosts (gmktec and trigkey) ────────────────────────────────
# Because this module lives in ../optional/, trigkey imports it automatically
# via its `listFilesRecursive` glob, while gmktec imports it explicitly. Both
# activate the proxy only when `services.portless.aliases != {}`, so the mere
# presence of this file on trigkey does NOT stand up an unwanted daemon — set
# the option on each host that wants it.
#
# mDNS resolves conflicts by suffixing (`jellyfin-2.local`, unpredictable
# across reboots), so give the two hosts distinct alias names. Do not publish
# `jellyfin` from both — pick `jellyfin-media` on gmktec vs `jellyfin-guitar`
# on trigkey, or similar.

let
  cfg = config.services.portless;
  aliases = cfg.aliases;
  enabled = aliases != { };
  # What a client asks for: 443 with TLS, 80 without.
  proxyPort = if cfg.tls then 443 else 80;

  reconcile = pkgs.writeShellScript "portless-reconcile" ''
        set -euo pipefail
        PATH=${
          lib.makeBinPath [
            pkgs.portless
            pkgs.coreutils
            pkgs.gnused
          ]
        }

        # Wait for the daemon to bind. `portless doctor` does not exist in 0.13.0
        # (the CLI has no such command, and polling it burned 30 seconds and then
        # raced the daemon for the route lock). The proxy writes its port into the
        # state dir once it listens, so wait for that file and then for a socket
        # that accepts a connection.
        port_file=$PORTLESS_STATE_DIR/proxy.port
        for _ in $(seq 1 30); do
          if [ -s "$port_file" ] && (exec 3<>/dev/tcp/127.0.0.1/"$(cat "$port_file")") 2>/dev/null; then
            break
          fi
          sleep 1
        done

        # `alias --force` overwrites an existing route, so rerunning the unit
        # changes nothing. Same idempotence contract as the *arr reconcile units.
    ${lib.concatMapStringsSep "\n" (
      name: "    portless alias ${name} ${toString aliases.${name}} --force"
    ) (lib.attrNames aliases)}

        # Drop any route portless still remembers that is no longer declared.
        # Portless persists routes to its state dir, so a removed alias here would
        # otherwise keep serving stale content on the next boot.
        #
        # `list` has no --json in 0.13.0; it prints one line per route, of the form
        #   http://sonarr.local:1355  ->  localhost:8989  (alias)
        # so the name is read from the URL.
        declared="${lib.concatStringsSep " " (lib.attrNames aliases)}"
        portless list 2>/dev/null \
          | sed -n 's|^[[:space:]]*https\?://\([^.]*\)\..*|\1|p' \
          | while read -r n; do
              case " $declared " in
                *" $n "*) ;;
                *) portless alias --remove "$n" || true ;;
              esac
            done
  '';

in
{
  options.services.portless = {
    aliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.port;
      default = { };
      example = {
        sonarr = 8989;
        radarr = 7878;
      };
      description = ''
        Map of alias name to the local TCP port to proxy to. Each entry
        becomes `<name>.local` on the LAN. Setting this to a non-empty value
        turns the module on; leaving it empty leaves the module inert, which
        is what lets trigkey glob this file harmlessly.
      '';
    };

    tls = lib.mkEnableOption "HTTPS with the portless-minted local CA";

    internalPort = lib.mkOption {
      type = lib.types.port;
      default = 1355;
      description = ''
        The port the daemon really listens on. Portless decides whether it may
        use a privileged port by testing `process.getuid() === 0`, not by
        trying to bind, so `CAP_NET_BIND_SERVICE` does not persuade it: as a
        system user it prints "Requesting sudo", gives up, and falls back.
        Rather than run node as root, the daemon keeps an unprivileged port
        and nftables redirects 80 to it. Clients still use a bare name.
      '';
    };

    lanSubnet = lib.mkOption {
      type = lib.types.str;
      default = "192.168.0.0/24";
      description = "CIDR that the firewall admits to the proxy and to mDNS.";
    };
  };

  config = lib.mkIf enabled {
    # ── Avahi (mDNS) ───────────────────────────────────────────────────────────
    services.avahi = {
      enable = true;
      nssmdns4 = true;
      publish = {
        enable = true;
        addresses = true;
        workstation = true;
        # Portless runs as its own system user and publishes each name with
        # `avahi-publish-address`. Without this, avahi sets
        # `disable-user-service-publishing=yes` and every publish dies with
        # "Failed to create entry group: Not permitted" — the proxy still
        # serves, but no name ever resolves on the LAN.
        userServices = true;
      };
    };

    # ── Proxy daemon ───────────────────────────────────────────────────────────
    users.users.portless = {
      isSystemUser = true;
      group = "portless";
      home = "/var/lib/portless";
    };
    users.groups.portless = { };

    systemd.services.portless = {
      description = "Portless proxy (LAN mode)";
      wantedBy = [ "multi-user.target" ];
      after = [
        "network-online.target"
        "avahi-daemon.service"
      ];
      wants = [ "network-online.target" ];
      # portless spawns avahi-publish-address to announce each name.
      path = [ pkgs.avahi ];
      environment = {
        PORTLESS_STATE_DIR = "/var/lib/portless";
        PORTLESS_LAN = "1";
        # Disable /etc/hosts sync — the box is a headless server, no browser
        # here needs a hosts entry, and portless would otherwise mutate a file
        # NixOS considers immutable.
        PORTLESS_SYNC_HOSTS = "0";
        HOME = "/var/lib/portless";
      };
      serviceConfig = {
        Type = "simple";
        # The port is explicit. Left to itself portless prints a fallback
        # notice and picks 1355 anyway; saying so here keeps the unit, the
        # firewall, and the redirect in agreement.
        ExecStart =
          "${pkgs.portless}/bin/portless proxy start --lan --foreground"
          + " --port ${toString cfg.internalPort}"
          + lib.optionalString (!cfg.tls) " --no-tls";
        Restart = "on-failure";
        RestartSec = "10s";

        User = "portless";
        Group = "portless";
        StateDirectory = "portless";
        StateDirectoryMode = "0750";

        # Needed so the unprivileged user can bind 80 (or 443 with TLS).
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
        CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];

        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectControlGroups = true;
        ReadWritePaths = [ "/var/lib/portless" ];
      };
    };

    # ── Alias reconcile ────────────────────────────────────────────────────────
    # Same pattern as prowlarr-reconcile: an oneshot that drives the running
    # daemon's CLI to match what is declared in Nix. Portless has no config
    # file we can pin from a module, so this is where the declarative story
    # lives.
    systemd.services.portless-reconcile = {
      description = "Reconcile portless aliases against the declared list";
      after = [ "portless.service" ];
      requires = [ "portless.service" ];
      wantedBy = [ "multi-user.target" ];
      restartTriggers = [ reconcile ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "portless";
        Group = "portless";
        Environment = [
          "PORTLESS_STATE_DIR=/var/lib/portless"
          "HOME=/var/lib/portless"
        ];
        ExecStart = reconcile;

        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        # `alias` takes a lock file in the state dir before it writes a route.
        # Without this the whole of /var/lib is read-only under
        # ProtectSystem=strict, the lock cannot be made, and the unit fails
        # with "Failed to acquire route lock" — which reads like a race and is
        # not one.
        ReadWritePaths = [ "/var/lib/portless" ];
      };
    };

    # ── Firewall and the port redirect ─────────────────────────────────────────
    # A browser asks for http://sonarr.local, which means port 80. The daemon
    # cannot hold port 80 (see `internalPort`), so nftables translates it in
    # prerouting. The filter chain then sees the translated port, which is why
    # the accept rule names the internal port and not 80.
    #
    # Only the prerouting hook is set. An output rule would be needed for a
    # request that gmktec makes to itself by name, but any such rule wide
    # enough to catch it also catches every outgoing request to port 80 on the
    # LAN, so tests from the box itself use the port.
    networking.nftables.tables.portless = {
      family = "ip";
      content = ''
        chain prerouting {
          type nat hook prerouting priority dstnat; policy accept;
          ip saddr ${cfg.lanSubnet} tcp dport ${toString proxyPort} redirect to :${toString cfg.internalPort}
        }
      '';
    };

    # LAN subnet only, matching every other UI on these hosts. mDNS on UDP
    # 5353 must be reachable or names never resolve on the client side.
    networking.firewall.extraInputRules = ''
      ip saddr ${cfg.lanSubnet} tcp dport ${toString cfg.internalPort} accept comment "portless proxy from LAN"
      ip saddr ${cfg.lanSubnet} udp dport 5353 accept comment "mDNS (avahi) from LAN"
    '';
  };
}
