{
  config,
  lib,
  pkgs,
  ...
}:

let
  # ── Tunables ───────────────────────────────────────────────────────────────
  bucket = "radio";
  mountDir = "/var/lib/radio/music";
  garageS3Endpoint = "http://127.0.0.1:3900";
  garageRegion = "garage"; # matches services.garage.settings.s3_api.s3_region

  # icecast.xml is generated by the upstream module into the nix store, so any
  # value we put here is world-readable. Use shell-style placeholders and
  # resolve them at runtime via envsubst (see the icecast unit override below).
  sourcePasswordPlaceholder = ''''${ICECAST_SOURCE_PASSWORD}'';
  adminPasswordPlaceholder = ''''${ICECAST_ADMIN_PASSWORD}'';

  radioScript = pkgs.writeText "radio.liq" ''
    settings.log.stdout.set(true)
    settings.log.level.set(3)

    music = playlist(
      reload=600,
      mode="randomize",
      "${mountDir}"
    )
    safe = mksafe(music)

    output.icecast(
      %mp3(bitrate=128),
      host="127.0.0.1",
      port=8000,
      password=environment.get("ICECAST_SOURCE_PASSWORD"),
      mount="/stream",
      name="trigkey radio",
      description="autoDJ from garage",
      safe
    )
  '';
in
{
  # ── Users ─────────────────────────────────────────────────────────────────
  # `radio` owns the rclone mount. icecast2 keeps its own user (defaults to
  # `nobody`/`nogroup` upstream — we override to a dedicated user). liquidsoap
  # is created by the nixpkgs module.
  users.users.radio = {
    isSystemUser = true;
    group = "radio";
    home = "/var/lib/radio";
    createHome = false;
  };
  users.groups.radio = { };

  users.users.icecast2 = {
    isSystemUser = true;
    group = "icecast2";
  };
  users.groups.icecast2 = { };

  # The nixpkgs liquidsoap module creates the `liquidsoap` user; we just need
  # it to traverse `/var/lib/radio` and read the rclone FUSE mount, both
  # owned by `radio`.
  users.users.liquidsoap.extraGroups = [ "radio" ];

  # ── Secrets ───────────────────────────────────────────────────────────────
  # Three env-block secrets, one per consumer. The icecast source password
  # appears in two of them (icecast needs to validate it; liquidsoap needs to
  # send it). Keys expected in each file:
  #
  #   radio/icecast-env:
  #     ICECAST_SOURCE_PASSWORD=...
  #     ICECAST_ADMIN_PASSWORD=...
  #
  #   radio/liquidsoap-env:
  #     ICECAST_SOURCE_PASSWORD=...
  #
  #   radio/rclone-env:
  #     AWS_ACCESS_KEY_ID=...
  #     AWS_SECRET_ACCESS_KEY=...
  sops.secrets."radio/icecast-env" = { };
  sops.secrets."radio/liquidsoap-env" = {
    owner = "liquidsoap";
  };
  sops.secrets."radio/rclone-env" = {
    owner = "radio";
  };

  # ── FUSE: needed for `rclone mount --allow-other` ─────────────────────────
  programs.fuse.userAllowOther = true;

  # ── State dirs ────────────────────────────────────────────────────────────
  systemd.tmpfiles.rules = [
    "d /var/lib/radio       0755 radio radio -"
    "d /var/lib/radio/music 0755 radio radio -"
    "d /var/log/icecast     0750 icecast2 icecast2 -"
  ];

  # ── rclone mount: garage bucket → ${mountDir} ─────────────────────────────
  systemd.services.rclone-radio = {
    description = "rclone FUSE mount of garage bucket '${bucket}' for liquidsoap";
    after = [
      "network-online.target"
      "garage.service"
    ];
    wants = [ "network-online.target" ];
    requires = [ "garage.service" ];
    wantedBy = [ "multi-user.target" ];

    # Inline rclone S3 remote called "radio" via env vars — no config file on
    # disk, secrets stay in the sops-managed env file.
    environment = {
      RCLONE_CONFIG_RADIO_TYPE = "s3";
      RCLONE_CONFIG_RADIO_PROVIDER = "Other";
      RCLONE_CONFIG_RADIO_ENDPOINT = garageS3Endpoint;
      RCLONE_CONFIG_RADIO_REGION = garageRegion;
      RCLONE_CONFIG_RADIO_FORCE_PATH_STYLE = "true";
      # Required so the named remote falls back to AWS_ACCESS_KEY_ID /
      # AWS_SECRET_ACCESS_KEY from the sops env file (without this, rclone
      # ignores them and tries anonymous access against garage).
      RCLONE_CONFIG_RADIO_ENV_AUTH = "true";
    };

    # rclone mount shells out to fusermount3; --allow-other only works when it
    # finds the setuid wrapper in /run/wrappers/bin (the in-store fusermount
    # exits with EPERM when called by a non-root user).
    path = [ "/run/wrappers" ];

    serviceConfig = {
      Type = "notify";
      User = "radio";
      Group = "radio";
      EnvironmentFile = config.sops.secrets."radio/rclone-env".path;
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.rclone}/bin/rclone mount"
        "radio:${bucket}"
        mountDir
        "--read-only"
        "--allow-other"
        "--vfs-cache-mode full"
        "--dir-cache-time 1m"
        "--poll-interval 30s"
      ];
      ExecStop = "/run/wrappers/bin/fusermount3 -u ${mountDir}";
      Restart = "on-failure";
      RestartSec = "10s";
    };
  };

  # ── Icecast2 ──────────────────────────────────────────────────────────────
  # Upstream module hardcodes the config path to the nix store, so we use
  # placeholders here and override the unit's ExecStart to render the real
  # config from the sops env file at runtime.
  services.icecast = {
    enable = true;
    hostname = "radio.ericsharma.xyz";
    user = "icecast2";
    group = "icecast2";
    listen = {
      address = "127.0.0.1";
      port = 8000;
    };
    admin = {
      user = "admin";
      password = adminPasswordPlaceholder;
    };
    extraConf = ''
      <mount type="normal">
        <mount-name>/stream</mount-name>
        <password>${sourcePasswordPlaceholder}</password>
        <max-listeners>200</max-listeners>
        <public>0</public>
      </mount>
    '';
  };

  systemd.services.icecast.serviceConfig = {
    EnvironmentFile = config.sops.secrets."radio/icecast-env".path;
    RuntimeDirectory = "icecast";
    RuntimeDirectoryMode = "0750";
    ExecStartPre = pkgs.writeShellScript "icecast-render-config" ''
      set -euo pipefail
      ${pkgs.envsubst}/bin/envsubst \
        < /etc/icecast.xml.template \
        > /run/icecast/icecast.xml
      chmod 0640 /run/icecast/icecast.xml
    '';
    ExecStart = lib.mkForce "${pkgs.icecast}/bin/icecast -c /run/icecast/icecast.xml";
  };

  # Expose the placeholder-laden config the upstream module wrote to the nix
  # store as a stable path that the ExecStartPre above can read. We can't
  # introspect the module's internal `configFile` derivation, so instead we
  # symlink to it via /etc.
  environment.etc."icecast.xml.template".source =
    let
      cfg = config.services.icecast;
    in
    pkgs.writeText "icecast.xml.template" ''
      <icecast>
        <hostname>${cfg.hostname}</hostname>

        <authentication>
          <admin-user>${cfg.admin.user}</admin-user>
          <admin-password>${cfg.admin.password}</admin-password>
        </authentication>

        <paths>
          <logdir>${cfg.logDir}</logdir>
          <adminroot>${pkgs.icecast}/share/icecast/admin</adminroot>
          <webroot>${pkgs.icecast}/share/icecast/web</webroot>
          <alias source="/" dest="/status.xsl"/>
        </paths>

        <listen-socket>
          <port>${toString cfg.listen.port}</port>
          <bind-address>${cfg.listen.address}</bind-address>
        </listen-socket>

        <security>
          <chroot>0</chroot>
          <changeowner>
            <user>${cfg.user}</user>
            <group>${cfg.group}</group>
          </changeowner>
        </security>

        ${cfg.extraConf}
      </icecast>
    '';

  # ── Liquidsoap stream ─────────────────────────────────────────────────────
  # `services.liquidsoap.streams.<name>` from nixpkgs creates a systemd unit
  # named `<name>.service`. We name it `radio-autodj` for clarity.
  services.liquidsoap.streams.radio-autodj = radioScript;

  systemd.services.radio-autodj = {
    after = [
      "icecast.service"
      "rclone-radio.service"
    ];
    requires = [
      "icecast.service"
      "rclone-radio.service"
    ];
    wants = [ "network-online.target" ];
    serviceConfig = {
      EnvironmentFile = config.sops.secrets."radio/liquidsoap-env".path;
    };
  };

  # ── Post-deploy one-time setup (manual) ───────────────────────────────────
  #
  # 1. Create the garage bucket and a read-only key:
  #      sudo garage bucket create radio
  #      sudo garage key create radio-ro
  #      sudo garage bucket allow radio --read --key radio-ro
  #      sudo garage key info radio-ro --show-secret
  #    Drop the access key + secret into `radio/rclone-env` via
  #    `sops secrets/secrets.yaml`.
  #
  # 2. Generate the icecast passwords (pick anything sufficiently random):
  #      openssl rand -hex 24    # ICECAST_SOURCE_PASSWORD
  #      openssl rand -hex 24    # ICECAST_ADMIN_PASSWORD
  #    The source password must be present in BOTH `radio/icecast-env` and
  #    `radio/liquidsoap-env`.
  #
  # 3. Upload audio into the bucket root (any S3 client; rclone copy works).
  #    Liquidsoap reloads the playlist every 10 minutes — restart for instant
  #    pickup: `sudo systemctl restart radio-autodj`.
  #
  # 4. In the Pangolin dashboard, add a route:
  #      radio.ericsharma.xyz  →  127.0.0.1:8000
  #    Newt is already running on this host (see `newt.nix`).
}
