docker-services:
    cobalt:
        keys.json: ENC[AES256_GCM,data:fkDP+3U5/IxcJVZ/3Sjm5NnnUL++9yhIBFFw36gRTKQ979QyDmbuhl9KhSmtc2rvJyo/lYo8sy1bYgDakeWaeGK2O6ibxHVD,iv:h0LX3eiqXOt/XG/Iyj4IO5ZDP6TaH8I8D+e3pu93lBg=,tag:V41kNNIrlw0Rs8nf8UNi2A==,type:str]
    dawarich:
        env: ENC[AES256_GCM,data:Sawmhz6Ym0VAD0+b29XDuW4E3K8vSb6pnXZXJWpKBmYmIppBo53EsRxqWiiq6vO/HxJ2t9e5KUX/XB5V2I64RqAr8plu55XVqLtP61xvOzuYmoO08MJ6EdFGHSQ0+qXIsxZAyJa60HE=,iv:WQREpgl6a+R2obkpXELwve8/hJqqokBYnMcsvuZwq5Q=,tag:q62xoz35Voq/obaiHc9s9w==,type:str]
    karakeep:
        env: ENC[AES256_GCM,data:bK7P8E/gGsmko3rZhSLdzPTVvPIAeLtdDkgq7fPqrfdyrHEColtmhh+uYqRpPDh6+C/xk8IuJGqYVJFf6u4LxU6maDkTsgPBqv28Phj6CSjkY7w6bSr2s5WYkw/UnajuPvtUJO2w/Ztc56UeQqFd1h+BdQRWdzZoqWpeIVR1wG+nS95HNxuUlrC9YLq5k5gS9iDEoJNJRbbE6YexznzraVTb9mre+S08u52Uxpyh6mvytypoWaZxELWzc732WFK8W8eMsRQ/YwJz9EoAVaw4fe4ndFRN5KGXfyFiqi+kA4tZnStG+fxrWbmmXmYBFmyx9Gr9AsB/EE35oljSANrsiDLHS8oCVmIqZS0pmevGaTB8uywkADxm8Pio,iv:9f2ZQ00htEu4tFzj/Ea6li925m/vAGZ8ZGSgtl906BI=,tag:1KU5ucVkJ04PuMjH+OQW5A==,type:str]
    keeper:
        env: ENC[AES256_GCM,data:GGk+k+wC3T4jeym//mnXXnOSG5W56xd3fY0TnEMXLx4kRT1If9WyjiDVrIW24oPhS5Hh/RjbBtyGtKeRSXi2OuWtecXzw+jMmj8bP3wIhqJfX085KIu40tqyf47Jz8KgVymJ2jWo/M2+zy47WK5RlQk8xZToyhMjLqZWmb/d1Er9Q7nYcDHjWRg2XKSlbtcLw3Y=,iv:XjFf5MVwCc81xW9V8t6uUfjoa/EozXv/sKb9oonplVA=,tag:5ilYj2AL9ylUk+y/HMxtWA==,type:str]
    koito:
        env: ENC[AES256_GCM,data:98/XyWzxrz4P/j2eV6uubPtTR2pAOKTGgMJO6pQ3p/wBrKzetweEv5fbBkXuZtd06mTmNnfmL0LkoeiqkRcmssQXlAKX5i/RTfQ/vl1mEIbRB8gXXuCICqaFpEkhAGo/XG1a7mvn81rPUeklf/Xi+xjWL1MHkYTxkBtbmqhX3+eeIsJ+6Bt/ECwkWbsk3VcugI6wl1Vk5n7PyVxCDDSdKeeHXVuTxfQQzmfu34TvIO6E9UOyi4bwUePIStkBAlWqFmkhR8JxmPTbdwQYSO6+WIKxgpt2b9ZNZcbrCE7924dsBeNkSc38QkSp8IkgtkdAt12rWsVT2Jb0jIwh8Dg=,iv:O1hje7MXMYkXtWRN1kNWRin9C1N56LBQLZsX8Ge53Us=,tag:voM44U076HfITojhOUDsGg==,type:str]
    rybbit:
        env: ENC[AES256_GCM,data:jMRQncqxqd+wESVJ4k47uZMVHKUyijWpbi0+0mlU5PtMUyfo8YD2WaapTfGbctEKGcU+5OK3swxHDoB56vqWHQxKOu12flwCzLPw+JjW0M0d8XlXSL8O/CU3ieovB28VuaRA3tbplL4mTFY68wPZUlmgljshcpAEJN0GJio49ZWPKELunlfzpW4swc/kmeFOmC+3j+Gi6S+gGLnSGB7xq4/SdVf3iWgWLyP+qgXm+E1rssxyhNjHMNOgdXSlbfZvVWKkyWekW2ieqXG7Aj3J+aVo3gqEDbRo7s+UC3nxQRCYqdsZ46qp2EY=,iv:oOoahXosQl7C/jyNvrjyLlpl8o6o9MtZtObPD6Mb7q8=,tag:jusPM3besBlrN6nOZeaCFw==,type:str]
eternatv-sidecar:
    env: ENC[AES256_GCM,data:KoynMCDAq1lgKnWkJgEuseWSnQx8swMR9oemreIy3BDSixZAPCerF0nlgczItIUJYwhi868=,iv:ojomz5Byr+CNrHmqNvVX0s0roFl3GlkLtNEwwr6bVGA=,tag:WyTfDBGnjEwojOKybDiaWQ==,type:str]
garage:
    admin-token: ENC[AES256_GCM,data:y9aKZocwqmFFEMbJYAa4psJOmswlVCRinnMspJhBk9U=,iv:tjjWBdWxJdpOlPBuW2Y55ZOpI7KoXrIhPFB+VFSB2yQ=,tag:602xpMW+khF/w4weZT9bUw==,type:str]
    rpc-secret: ENC[AES256_GCM,data:yNRYh5LQq9ZccmTqOhmYW8iYS+DQN2r5rchIdRoCXJh8fdmG8DoPFw0/pH6r1he8+UjbpMzni56sucpI/o2bzg==,iv:t1phwKdRCScdVGklx/ef5a/mk1fjkE1643BsHQgEIpY=,tag:lVnizbEI4YI0xmnVTScYuw==,type:str]
garage-webui:
    env: ENC[AES256_GCM,data:QWx8OcyS4IXrCGWnZZAm5g3gT/y2QSlv9Zea6dH8taP7xIz2v6F1kUV5l386yls=,iv:75vPfAeH3y4H7bGD0PBjRDBtcblwHOIiLps2EcQHegQ=,tag:edbesa/vs1rxvIHZMV96vw==,type:str]
grafana:
    env: ENC[AES256_GCM,data:FxL6hvP3pffop//V7av9fUhxZ8WTnqq8qKhClO2b4CaMg69e+z8z/FM=,iv:0O/2izBMvhbPbQywao5CeibzuNeWOf66HdXAAfpxY6s=,tag:g34GUmIsKwE6/JnVK52Klg==,type:str]
guitar:
    rclone-env: ENC[AES256_GCM,data:lodVFZm3tdvW5eHRzv7jZ1NGEuoW/gzXVnMzks/zI37gwbNz2qAMAUEeClLEnLd7b4jUIN0zGxs1s+xtORPV0oY/LEyFUBd+hJNaUK1sLZvofheRA3hzo+3X2uw1A2E7izhyQ582Cl+CjnaRqLJvc/eTDvzHFKtg+WDM/i18MKCpFPyK,iv:v3v6WSoXIOjT6wbpWgM0AY9YrALitL+iWjjFr6mDhe0=,tag:R5a7ssGLns5mvVCymualVg==,type:str]
homeassistant:
    token: ENC[AES256_GCM,data:V+TA1TSNaH9/c+j8K4X6jCBpKAyhe9LqVE2Ix4/fSeYLepi/kX1C12PEeFB7p/v1bB/YCtw/HnqxLd73HRCqMtk7yuMhyIY5HGBvn1z9okyt2xdt90qboIaMuULmFnI4UtXHk0gJjoTDdLQb7uFbp6FP18JJcsY42TxAqlR0RrNhXVZ9+0spe9rK+HfPQ7EHlqxTN8rBO8FqMprpoqksRToK6mk04VvkCs8B7lGxH2wZbRFvrDUm,iv:uM17gCbfX2EBk3piDqMIIgTWeaPFMDnDgU45WWPr3NQ=,tag:+1jMOraLXZ8tBnTY3RY70A==,type:str]
newt:
    env: ENC[AES256_GCM,data:eHppbG8f9WbFlas2wH0NkS0Jk66JWkOpAiTT3jHqs8r98H/kJa874pGGzHLuymIWtNC6nq3HqMChqkj1qdmg8cJkT2ZtLpbS0NYnHWkJhNja4GsJ3Q==,iv:nSMTLLvTy9ztR3t4glqgzUSPxzX8ya5j1kcwOb9WQCk=,tag:5cH2UzeA7OaWvo1XgDcKjg==,type:str]
pirousync:
    env: ENC[AES256_GCM,data:m777IEHsO7OjM4Hpg2Qo0P6jkjmqeat2d84AxKdyojSqfOrF6VoHuk0BNOhG8qOZrCUZ1OL9wbb8K6zaYEc0w+POX6jPX9KBLihLvSnmoHBQLRpb7WghDMaB+OYjZi+eZl4YSpkpCf9OqEmDJjiCoPt7OvyfrkKDVKOfweyfgCnl8eA6KNTCZtNuqHOurpmvrSWJCOwcMT9TA/EvBNT32epwotMVQu3IvzwlQRhU0V5fXh5TduHhEl2wrXUPybw5/b3ohZKpfdFRmrYPBrflfzeJEeFHvdZwfrAXs6UatgeEpMWFyxzrgVkekYjzHso2shltGB4XFAOXzQvTL5wQNGD+AIO3DBp53VGGPqIrO88YmP9oWYcQMKrxM4h47tz7YSbmSRnd/wtLEgBU6/8KhPrw6ZmUGPOdNKOR4AJekDctyfvhXVyJ19GHMzKxLDFR5UjL/U0TeZ5EQBGYNPc20szP1HFXpEVXRReIfk3B6FQ5ymAvPPpxuVE1RFCPaHiNZ34WBZQMJb9e0bQb0/75BTjzq2f/jdtnSw==,iv:BFJCR348AimFzZjzImwSDjXHToptNP2NqlVYVVso3gk=,tag:vdUQ2nfO25Fi79DAZgDUjg==,type:str]
radio:
    icecast-env: ENC[AES256_GCM,data:PkpjvBEJbmtGsARsageKwGCgTOGWC7JXrn+6uBgdQKIXWsPbMZnPXYCowLBCrJ0bYqHakk+b2sW53ELycYcEkYn3++AEA0Xme1EPCdbQ5fqkDooQbq+yNGLW60YpCP1DMVoMntl+XSHDptTjVubBcHz33D6tj+sqSF1dEKZ1x2bBaJl5c2J2/r3/eaRdKVSDmw==,iv:AoqOARvuoCt7nN0D2LzJ2gWsTgfluY/zdw31LfF1Cwg=,tag:1nuNHhjqiSDtS9xzAilFkA==,type:str]
    liquidsoap-env: ENC[AES256_GCM,data:dSTeOO0mkCZJhzThOKlXu4GI4VwmKeTEjhJLLwCdT30dnP9PcTjzKVmZ2YydZF/++266NPOSTZZ5Aq5Nl9tku4FYLR3ahNix0g==,iv:B5A1us7TX+CjkSbuKznyIRguHJ6bFcZzldo6B6JUvDc=,tag:2lZnViWSKfQKxMp2LDsiQA==,type:str]
    rclone-env: ENC[AES256_GCM,data:sIJExZWlkcoHeColXg+njkLiALvjBJZFkjtCO057gBzx5/t4aej1V3bBd+bo6e7OyunPXixuTCypULEJyR4TVq7TsTGbEhjWgK41RSomvfr+R1pkNfqt+USIpnqralc6ZCSXX4q69DLTKM76JLmsBY//cvgerUmcDhzY8Vj4NDayXCB5,iv:IKrACmsLfgLrzLVMDT+iM5R3nebBiSWEO+f+xPaVHd0=,tag:Z4ezShXaK7bZR9X1NqYamQ==,type:str]
radio-video:
    rclone-env: ENC[AES256_GCM,data:PB5yL2wizD7sQCZrcN6XeiIjOAxK7SAEByT2qO4zQjkWIeqMOfZ5d/OsM9dgxHx4PO+RPz8uhgmd1ensIVUEzWienKpDvUZldwrARtUtkdnnJH+htSC40QVkJYA5m7s9VfWtqMSFcCJnDSeGcd2zSou1FFwIpfbq1cwmfKqeGXPY2ymz,iv:EJMqFqhih+EAgW5MuXZbwsLROUjLxvHatE4LNtImw9M=,tag:T0MVpHzVrJjuioczUXRtKg==,type:str]
restic:
    immich:
        env: ENC[AES256_GCM,data:mEc8N5SssQJdVM8CT/Oj8xqnKDJ/jUqRB5sFPpqMZNLSDRGmefGkRsSIN4GtstNJqdl0RkUlhI+YkDMrz7kEQT/jOs7ZrKKcmNi68gDS3JthFFWPMbQWBwvjEa3sUjklz+x1AVKF4A3BFuxWqZLADJ70nKUIQh83jamh8L+UOLbKhP+zkHQFcNLFlyUFV/cxlSi6hnAZCWzjaySI6MKX20OGIkIx04M5GvexdneEvJeP0w0ApxlD2SuufQRj84ueeZMXdlmm2pPFXcDUbSb4elOl,iv:Aty7I6uwUX0i00WoDAULNqh9/QWz1NxPiHH6UXJVbLQ=,tag:Dk8axNv17W/SS4hidLgkmA==,type:str]
        password: ENC[AES256_GCM,data:d67tUeykFMQyZ/MFHJJzkFXj06CjCP/+RccrjIQ9Wo9BTY5zRwdmaAgXPP6uCCYELZKcWQig7dTQ16WwQu0Ivg==,iv:E9c9zJMtAyaHbI/1H0CEeet6i9velF+TrUdRoUXxE+A=,tag:Fk9DsfB0h+FJ6QQEmUmQdg==,type:str]
strava:
    env: ENC[AES256_GCM,data:WZD1ByQirjPiL/63kgDTVvMcNQ0jiK7vrjv8UF6YAVmOVh6iKm06zy0gw/7MEsO3gInipUt18S7wZXTPFpBm3EZU2YsInGMsWgEUSVjl47UrzfKLPUiEGFa2teqJYqjuXJGtpVeCiXvgfSdpBbOGoa+s58qa+R5J5w0Tenz1XEeC4XSotezHCnn+D+viMA2La7WmoA==,iv:8tn5u8WD/v2ShijQ8/4/Xj2pQsdPRjE+ZmOTKvtNOk0=,tag:dIvHKD4oHQGknxijAjZkEQ==,type:str]
tailscale:
    authkey: ENC[AES256_GCM,data:gllQHdo1C8MTSJ5F42cSSstWbY/EFpqNNt7MN1Clx5rTfJWD/scq9YeXkfYgw5LYj8sV+8aIfVoAP7QEKQ==,iv:1SpDY+4nkvkuJgjVavoEjE7c5GiCrWpvpxcV+kfKmRM=,tag:ZJi0SFI52N7F2J3+nZ2fEQ==,type:str]
user-password:
    eric: ENC[AES256_GCM,data:xOc6ZvPsBtVfmzjh1RFEt8R/gM8ziWq/R1dcF7kWgR3GbxFa5QZT44LleiCpGgYaEziw3UvPY2FU+qfjM7Y9A4s5N7nsVX2B2FPApwJRt6R/eCqvXLrJemuKM0FxB7SieuT4EVyaXEcPDg==,iv:Jw2AT+2oETjDiQYgNj+2XXzt6cGAvVY0cY/vbLyNSMg=,tag:QyepRrD3IBV9rQNoHokYTA==,type:str]
vaultwarden:
    env: ENC[AES256_GCM,data:kx//5o9h6YeFbX53TMz9qvyoHBfnMcp1So8IA/RkclP9VzPJnNAxGc2zuHmrHMiYY4DZa5XCtsr0Uv1M9HjT35i8us9QFyxtDIemXv8=,iv:t2rY6BEE1+PQ6GvTq8gWKCbpmi/+1Hzo6JfZtiYwQ5A=,tag:/oBHyUh2DwfRtz34iLakHQ==,type:str]
whisper:
    env: ENC[AES256_GCM,data:VoLXk8qFAT8NyRErUCvLOtPe2PEESZcN9XtcbmL9zDZJ6nn5je4y3W4zm1A/V6M=,iv:qB5uvq5UGsdPhIdod4sxDLRTi0M8ziaFWqFJ/tFqEtc=,tag:9ZIUJq6l9lSFqjXWp9AESA==,type:str]
sops:
    age:
        - recipient: age1wq3pdga9uclmyseewafgyrtyyrd764eurnr444uandr6d3k9kfdqlmaqry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYkFZanFac1Q3c3piNjhr
            UHJqdHVRM0NOaytSbWh6bFRlK3ViS1BTemg4CmpPWnFRRklSMTd4cHRGLzdtbUhi
            RjJSRkdPc3FlbkdkaVZFUDBJdFU2eEkKLS0tIHBxQldOektINktFS2NET3RZTUpa
            WW1wMi93UCtRVEE4bkJhUjdmZVRwWGMK5XVQ2m4e3LDrfOe9JMAAFWDs1NeBfeq/
            lfekQ10lUWx2qgeB4UiZ9noGXmtaJhFhMkyOhNGNIUbwse7owDdOrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16kn2xl9adz9864vanswgysjtlmecpa7fmmmad2jlg8rdm6rsyylszpn6nd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV0N4dWlMb3ZSWHdrMnQ1
            UnN5cjdJTVFScmw2MUUyQmVhMERKazdSdW1rCm8yamxFOG13bk16cDRBMFgyK294
            Um56WWFNWFdXa2hYVTRESWEzdzg1V0UKLS0tIDJ6MWlIYTc3Q2pqTWtMUUtpTGEx
            aWxwalVhb3VxSWROSzRMTExjRVNlVTQKAoGTigUl2IUPCgDk1XRac7+6VhjFkXHJ
            KvYW3k5DOOHD8MngFZNI4i9dLkLWuDFEgcpf8xAT8gTQbOdOfSAuVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17yqlhhgg7zwvgjk277eu9cdepake0y3zaaz9gkgwcjgkl6d4eguskhzg55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SGdHZTA0cXRQdWd2TGNS
            RTE5eFpoUVdlRkJTZDhhR2ZGWmg5TUxkQWtrCkpwbUlnYThYcW5aSWJWZ2tjUmhr
            Zkp3aHhjS2MwbjlBbnFsekEwSmlDUWcKLS0tIFpFdEZLd2xNc0Jla0N2UVlEREJk
            K0E1U3lyY0lRVXhFdlRFdEVKTWltNGsKJzUYzLtRoPlzd54wkmYPX/l9sXk/++i6
            fmWpjDjdrMNKHH8Jadf21jvFuacldM6ZlUNRGeUmJntQJr20f/y8mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T20:17:43Z"
    mac: ENC[AES256_GCM,data:+vHR7Jx6GyFNI8VKqBvuZs+K4NKlyCjNOFo+FI3D8j97tRGaJoEXruOlUEdiSAXXmg9ySifbK6zcRUAkRtt+kHgj/wUfNCIu6HOo6lf4smgem2cm2m5AgtrMtgpbM57EI3/3uV7YIIYmTPS7ZCpUZfygPeJU1Sjym3F2HKd+ol8=,iv:xfcn0I2DM6x4+cFLPH5d7s3AeKJqz/Lj8fyx3Ci/Vqk=,tag:TzdFxcqJQRpv6kb0+KCaYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
